# Generated by Django 3.0.8 on 2024-06-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(max_length=200),
        ),
    ]
